import React from 'react';

const Contact = () => {
  return (
    <div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum veniam debitis accusantium mollitia commodi, soluta nulla natus iste assumenda, sunt neque. Cum odio cupiditate, numquam beatae animi magni inventore assumenda reiciendis impedit fugit? Nulla, similique. Delectus debitis est ullam perferendis explicabo incidunt, error optio recusandae a magnam tenetur iure cupiditate, excepturi eaque pariatur ratione, voluptas harum nobis sit corporis hic cum provident blanditiis odio. Cumque, corrupti ad ab suscipit maiores neque. A, voluptate ad. Praesentium vero facilis expedita temporibus, voluptatibus distinctio. In reiciendis alias mollitia, accusamus numquam iure doloribus ducimus autem corporis vitae corrupti illo possimus eveniet voluptatum provident magni rem? Recusandae impedit cupiditate corporis explicabo veniam temporibus nesciunt iste in. Exercitationem assumenda saepe suscipit totam sint voluptatem sequi explicabo eligendi veniam itaque praesentium accusamus facere tempora, aliquam quibusdam consequatur deserunt labore dolore sapiente tenetur? Eum laborum ducimus recusandae, beatae at vero optio labore fugiat hic placeat nobis quasi quas corporis eius numquam libero incidunt voluptates cum sint? Quam iusto voluptates asperiores maiores illum, repellendus ipsam voluptatibus mollitia quae veritatis molestiae perferendis nemo reprehenderit facilis vero laborum dolore corrupti, eaque nesciunt beatae assumenda tempore aperiam? Dolore ipsa a quod aliquam animi sapiente, atque veritatis molestiae nobis harum eveniet, accusantium enim velit hic tempore cupiditate aliquid dicta vero impedit libero possimus! Vitae corporis tenetur officia ea pariatur iste consectetur non quae veritatis explicabo. Fugiat culpa possimus dolorum ipsam eaque ut ab consequuntur consectetur labore inventore, expedita excepturi quos vel nisi voluptatem ratione accusantium magnam sequi est? At, repellat, libero praesentium magni minima quas quia deleniti corrupti veritatis, veniam voluptas natus. Dicta repudiandae vitae atque nostrum optio adipisci, soluta ducimus, cumque sit, amet expedita. Reprehenderit officia aspernatur possimus, fuga quam rem reiciendis laborum inventore molestias vel velit voluptatum amet harum delectus earum doloremque deleniti, nesciunt quae natus laudantium quaerat. Cupiditate, reiciendis itaque?</p>
    </div>
  )
}

export default Contact